name: shelf_mustache
description: Mustache template rendering integration for shelf
version: 0.0.1+1
repository: https://github.com/felixblaschke/shelf_mustache

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mustache_template: ^2.0.0
  shelf: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
